server:
  port: 8280
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order?useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: cn.zuoye.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.zuoye: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  cloud:
    nacos:
      server-addr: localhost:8848
